export const routes = {
  HOMESCREENS: 'HOMESCREENS',
  BOTTOMTAB: 'BOTTOMTAB',
  CARTSCREENS: 'CARTSCREENS',
  NOTIFICATIONSCREENS: 'NOTIFICATIONSCREENS',
  PRODUCTSCREENS: 'PRODUCTSCREENS',
  PROFILESCREENS: 'PROFILESCREENS',
};
